repos:
  - repo: local
    hooks:
      - id: node-eslint
        name: eslint
        entry: npx eslint --config eslint.config.js --fix --max-warnings 0 --no-warn-ignored
        language: node
        require_serial: true
        types_or: [html, javascript, json, jsx, ts, tsx]
        # Ensure eslint and its plugins are installed via package.json
        # and accessible in the environment where pre-commit runs.
        # additional_dependencies:
        #   - eslint@9.16.0 # Keeping this commented out or removing it
